services:
  orderprocessing.api:
    image: ${DOCKER_REGISTRY-}orderprocessingapi
    build:
      context: .
      dockerfile: OrderProcessing.Api/Dockerfile
    ports:
    - 8080:8080
    - 8081:8081
